### ISSUE TITLE
invalid json versatiles/admin.geojson

### ISSUE THREAD

**Issue by ladnet** [versatiles-org/shortbread-tilemaker#2]
in versatiles/admin.geojson malformed json data at line 1 near: "name_latin":"","name_full"

this cause an issue on versatiles/get-shapefiles.sh when using ogr2ogr  on line 29

ogr2ogr -f "ESRI Shapefile" "data/admin-points-4326/admin_points.shp" "versatiles/admin.geojson" -t_srs EPSG:4326 -lco ENCODING=UTF-8

**Comment by MichaelKreil** [comment]
@yetzt same problem here.
Now I can't generate the new planet. :/

**Comment by MichaelKreil** [comment]
that should fix it: f68b9fe0fced9c6b47aecd421e63e95598b7736e

**Comment by yetzt** [comment]
Oof, it appears i messed it up with search/replace. Thanks for the fix @MichaelKreil.
