### ISSUE TITLE
Ocean Missing?

### ISSUE THREAD

**Issue by koufopoulosf** [versatiles-org/shortbread-tilemaker#3]
Hello Team,

It seems that ocean/water is missing from a part of Greece:

![image](https://github.com/versatiles-org/shortbread-tilemaker/assets/66564413/6d4e69b9-c573-4ddf-91a3-f6ba5af8ae64)

Could this be fixed?

Thanks in advance for your time!

**Comment by yetzt** [comment]
This appears to be an [upstream problem which you already adressed there](https://github.com/geofabrik/shortbread-tilemaker/issues/18).

**Comment by koufopoulosf** [comment]
@yetzt I mentioned it here as I created an MBTiles file with both this repo and the repo of geofabrik.

From current repo I get the ocean layer added:
![image](https://github.com/versatiles-org/shortbread-tilemaker/assets/66564413/a9ff2594-8edc-4e70-b331-e33cf4f4ec5e)

While from Geofabrik the ocean is missing completely:
![image](https://github.com/versatiles-org/shortbread-tilemaker/assets/66564413/fc9d9121-c3c8-4201-89e8-c4002c295747)

Any ideas of how we can fix that?

Thank you very much for your reply, I appreciate it.

**Comment by yetzt** [comment]
this appears to be an intermittent bug in tilemaker:
https://github.com/systemed/tilemaker/issues/417
https://github.com/systemed/tilemaker/issues/401

**Comment by koufopoulosf** [comment]
I will make an issue on tilemaker repo as well. Do you think there would be a way of solving this issue? Thank you.

**Comment by koufopoulosf** [comment]
Of course, the tile is missing here as well: https://tiles.versatiles.org/#8.22/37.787/24.45

**Comment by yetzt** [comment]
i'm not too versed in the inner workings of tilemaker.

**Comment by MichaelKreil** [comment]
We still need a fix!
I generated a new planet, but there is the same problem:
https://tiles-dev.datenhub.net/map.html?url=/tiles/osm/#8.03/37.685/24.434

**Comment by koufopoulosf** [comment]
Solved here: https://github.com/versatiles-org/versatiles-rs/issues/27
